# Generated by Django 4.1.7 on 2023-03-13 19:38

import airline_server.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_server', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', airline_server.models.user.UserManager()),
            ],
        ),
    ]
