# Generated by Django 4.1.7 on 2023-06-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_server', '0002_flight_place_ticket_route_flight_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
